version: '3'

services:
  front:
    build:
      context: .
      dockerfile: front/docker/dev/Dockerfile
    ports:
      - "80:3000"
  back:
    build: 
      context: back
      dockerfile: back/Dockerfile
